### PR TITLE
Add zone grouping for devices

### PR DESCRIPTION
**Pull request by vincent8balls**
Add device zone grouping into device selection settings. So you can better see in which zone a device is.

### CODE REVIEW

**Comment by vincent8balls** [comment]
@AdyRock There is still a bug in display configurations, I am running into after using it. Wil fix this later today.

**Review by AdyRock — DISMISSED** [review]

**Comment by AdyRock** [comment]
It looks like the zone is in `zone.name` and not `zoneName`.

**Comment by vincent8balls** [comment]
@AdyRock Thats strange. Is there a difference between devices? Because its working on my device. What device do you have?

**Comment by vincent8balls** [comment]
> I am testing on a HP2023. Maybe Athom have made a change to the API between the Homey types, What are you using?

I am using Homey from 2017 (Old one, haha). There its using zone.name. 

I can check if its working with your change on my device as well. Can do it tomorrow. Otherwise, we can do something like this:
`device.zone.name ?? device.zoneName`

**Comment by AdyRock** [comment]
I will try it on my old Homey this evening to see what I get then. The main issue is the Display gets confused if more than one Homey tries to configure it, hence I stick to my new Homey (which I still use for testing only).
I have tried to find a way to cope with multiple Homey controllers, but at the moment the Configuration is one way.

**Comment by AdyRock** [comment]
I found a bit of time to check on my old Homey and it seems that provides both zoneName and zone.name. So if we go with zone.name that will work on both.

**Review by AdyRock — APPROVED** [review]
I'm going with this latest code.

**Pull request merged**
